name: Check Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build application
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
