name: Check Font gen

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Generate font files
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: font-gen
